
dict2 = {
'corection': {1: {'id': '1',
                     'thumb_url': 'https://goo.gl/images/jSK3Aa',
                     'title': 'Корректор лента',
                     'price': '43',
                     },
                2:  {'id': '2',
                      'thumb_url' : 'https://goo.gl/images/zgTSzc',
                     'title': 'Корректор карандаш',
                     'price':'48',
                     },
                 3: {'id': '3',
                    'thumb_url': 'https://goo.gl/images/4gDzf2',
                    'title': 'Корректирующая жидкость',
                    'price': '44',
                    },
              4: {'id': '4',
                    'thumb_url': 'https://goo.gl/images/ByhAKk',
                    'title': 'Мини-корректор карандаш',
                    'price': '25',
                    }
                },
 'files': {1: {'id': '1',
                     'thumb_url': 'https://telegra.ph/file/d105a260feae561ce5ca7.jpg',
                     'title': 'Файл вкладыш',
                     'price': '2',
                     },
                2:  {'id': '2',
                      'thumb_url' : 'https://telegra.ph/file/c76586b16cf5a6cfba070.jpg',
                     'title': 'Папка-скоросшиватель',
                     'price': '12',
                     },
                3: {'id': '3',
                    'thumb_url': 'https://telegra.ph/file/254301366c1a6e94cf89d.jpg',
                    'title': 'Папка-конверт на кнопке А4',
                    'price': '25',
                    }},
 'pens': {1: {'id': '1',
                     'thumb_url': 'http://www.ivblank.ru/image/cache/catalog/goods/ruchka-biefa-blu-600x600.jpg',
                     'title': 'Ручка шариковая синяя «Эконом»',
                     'price': '6',
                     },
          2: {'id': '2',
                     'thumb_url': 'https://telegra.ph/file/a0e04510744c9fc18ddb7.jpg',
                     'title': 'Ручка Office Style шариковая синяя',
                     'price': '9',
                     },
          6:  {'id': '6',
                     'thumb_url': 'https://telegra.ph/file/29084fc493c35b33a29ad.jpg',
                     'title': 'Ручка шариковая синяя автомат Erich Krause',
                     'price': '26'},
          4:  {'id': '4',
                     'thumb_url': 'https://telegra.ph/file/96e6e824d381c55fbcf79.jpg',
                     'title': 'Ручка черная гелевая',
                     'price': '21'},
          5:  {'id': '5',
                     'thumb_url': 'https://telegra.ph/file/2716c58ed9234a65bf508.jpg',
                     'title': 'Ручка черная шариковая автомат',
                     'price': '18'},
          3:  {'id': '3',
                     'thumb_url': 'http://mystatum.ru/upload/iblock/29a/29ab053d024085d8910bc8c7bd9ee103.jpg',
                     'title': 'Карандаш чернографитный, с резинкой',
                     'price': '6'}
}
}


dict_price = {
'Файл вкладыш': 2.0,
'Папка-скоросшиватель': 12.0,
'Папка-конверт на кнопке А4': 25.0,
'Ручка шариковая синяя «Эконом»': 6.0,
'Ручка Office Style шариковая синяя': 9.0,
'Ручка шариковая синяя автомат Erich Krause': 26.0,
'Ручка черная гелевая': 21.0,
'Ручка черная шариковая автомат': 18.0,
'Карандаш чернографитный, с резинкой': 6.0,
'Корректор лента': 43.0,
'Корректор карандаш': 48.0,
'Корректирующая жидкость': 44.0,
'Мини-корректор карандаш': 25.0,
}




